### ISSUE TITLE
Extraneous spaces around "<-"

### ISSUE THREAD

**Issue by basille** [lorenzwalthert/oneliner#1]
Thanks for this great package. However, despite the `README` showing otherwise, there is a major bug that really undermines the usefulness of the package: `oneliner` should remove extraneous spaces around `<-` and not waste extra characters.

```
sum <- function(x,y){x+y};1+1
```

should really be:

```
sum<-function(x,y){x+y};1+1
```

**Comment by lorenzwalthert** [comment]
Thanks for reporting. I am aware of that. Since that package is more of a pet project and I did not spend a considerable amount of time on it, there are edge cases in the sense that spaces could be removed but are not. The thing is that some tokens need spaces around them because otherwise they are evaluated to something else. `A<-B` is not `A < -B`  for example. That is why I excluded some tokens from the styling, but I agree that we could remove spaces around the arrow assignment, but probably not around `<` and `>`.

**Comment by basille** [comment]
Well, I was mostly reporting in the spirit of April 1. :)

But since we're at it, yes, very good point. Then, it seems to me that `oneliner` should ban spaces altogether, as a core principle, and should thus ensure that `A < -B` is converted to `A<(-B)` automatically (which should be good practice anyway). Probably easier said than done.

**Comment by lorenzwalthert** [comment]
Well I think that's doable, we add curly braces with the tidyverse style. But it's not a top priority for me now 😊. But let's keep that issue open. Spaces should be removed around arrow assignment with 8ac2e6c since this case is unproblematic.

**Comment by lorenzwalthert** [comment]
Simplest solution is to replace `<-` with `=` always.

**Comment by lorenzwalthert** [comment]
Should work now.
